name: skyblock
main: com.naquackes.Plugin
version: 1.2
api-version: 1.15
commands:
  backrooms:
    description: teleports player to backrooms
    usage: /backrooms
  hub:
    description: teleports player to hub
    usage: /hub
  build:
    description: teleports player to builders lounge
    usage: /build
  factions:
    description: teleports player to factions world
    usage: /factions

